//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResortManagerSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AttachService()
        {
            this.ContractDetails = new HashSet<ContractDetail>();
        }
    
        public int AttachServiceId { get; set; }
        public string Name { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<int> Unti { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractDetail> ContractDetails { get; set; }
    }
}
