//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResortManagerSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractDetail
    {
        public int ContractDetailId { get; set; }
        public int ContractId { get; set; }
        public int AttachServiceId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual AttachService AttachService { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
