//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResortManagerSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public int ServiceId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Are { get; set; }
        public Nullable<int> DoubleS { get; set; }
        public Nullable<int> SerciceMaxPeople { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> RentypeId { get; set; }
        public string StandRoom { get; set; }
        public string DescriptionOtherConvenience { get; set; }
        public string PoolArea { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual Ren_Type Ren_Type { get; set; }
        public virtual Service_type Service_type { get; set; }
    }
}
